apiVersion: v1
kind: Pod
metadata:
  name: app-node
  labels:
    app: app-node
spec:
  containers:
  - image: dinghy123/app-node:latest
    name: app-node
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-node
spec:
  type: LoadBalancer
  ports:
  - name: "app-node"
    port: 3000
    targetPort: 80
  selector:
    app: app-node
